### ISSUE TITLE
TypeError when invoking canopy

### ISSUE THREAD

**Issue by mbadros** [jcoglan/canopy#43] opened 2020-06-30 15:34 UTC
Hi -

I installed canopy using npm. I tried one of the simple examples to make sure it compiled to Python. I created the digits.peg file in the working directory and got the following error. 

Any ideas?
Thanks.

`F:\Users\otheruser\Documents\Python Projects\canopy_practice>canopy digits.peg --lang python
invalid options argument
TypeError: invalid options argument
    at optsArg (C:\Users\username\AppData\Roaming\npm\node_modules\canopy\node_modules\mkdirp\lib\opts-arg.js:13:11)
    at mkdirp (C:\Users\username\AppData\Roaming\npm\node_modules\canopy\node_modules\mkdirp\index.js:11:10)
    at write (C:\Users\username\AppData\Roaming\npm\node_modules\canopy\bin\canopy:32:5)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\canopy\bin\canopy:37:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)`

**Comment by jcoglan** [comment] 2020-06-30 17:54
This looks like a duplicate of #37, #38 and #40 -- could you check and confirm?

**Comment by mbadros** [comment] 2020-07-01 15:21
Many thanks for the prompt and useful pointer. I followed /longhotsummer/canopy's fix and it works perfectly. Apologies for not catching the issue myself -- As a novice with npm and Javascript, I had started to troubleshoot by searching unsuccessfully on Google to find help with JS or the command line error.

**Comment by jcoglan** [comment] 2020-08-03 12:42
This has now been fixed by merging #38.

**Closed by jcoglan** 2020-08-03 12:42 UTC

**Comment by jcoglan** [comment] 2022-04-01 11:51
This should now be fixed as part of the v0.4 release; see https://blog.jcoglan.com/2022/04/01/announcing-canopy-0-4/
