### ISSUE TITLE
TypeError: mkdirp is not a function

### ISSUE THREAD

**Issue by apoorvamohite** [jcoglan/canopy#71] opened 2023-05-25 07:32 UTC
```
TypeError: mkdirp is not a function
    at main (C:\Users\usr\AppData\Roaming\nvm\v18.16.0\node_modules\canopy\bin\canopy:56:11)
    at run (C:\Users\usr\AppData\Roaming\nvm\v18.16.0\node_modules\canopy\bin\canopy:64:11)
    at Object.<anonymous> (C:\Users\usr\AppData\Roaming\nvm\v18.16.0\node_modules\canopy\bin\canopy:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by jcoglan** [comment] 2023-05-25 16:19
This is a duplicate of #68 and a fix has been committed but not released yet.

**Closed by jcoglan** 2023-05-25 16:19 UTC
