### ISSUE TITLE
Installation via npm does not work

### ISSUE THREAD

**Issue by rbtsv** [jcoglan/canopy#54] opened 2021-09-08 07:06 UTC
Hello, I tried to install canopy via `npm install -g canopy` about a week ago and got the app that does not work. The build from the git sources worked well for me. Could you please update the npm package?

**Comment by jcoglan** [comment] 2021-09-08 08:02
This is a duplicate of #53, #52, #48, #46, #43, #40, #38, #37.

**Closed by jcoglan** 2021-09-08 08:02 UTC
