### ISSUE TITLE
installation via npm is broken

### ISSUE THREAD

**Issue by lubieowoce** [jcoglan/canopy#52] opened 2021-07-26 12:07 UTC
the `0.3.0` version available on NPM is currently broken. the issue is that its `package.json` puts no version bounds on `mkdirp`, so it gets `mkdirp==1.0.x`, which had a breaking API change from `mkdirp==0.5.x`, the version canopy 0.3.0 used. this was actually fixed in https://github.com/jcoglan/canopy/commit/fc11abe23905c8da76a7c405e0b6359741c75090, but  never made it into a release.

as a workaround, i put up a mirror that installs correctly at [lubieowoce/canopy-compat](https://github.com/lubieowoce/canopy-compat/), but it'd be nice to have an official release that can be installed via the usual channels :)

**Comment by jcoglan** [comment] 2021-07-26 18:48
This is duplicate of #48, #46, #43, #40, #38, #37, possibly others. I am working on the next release of canopy and it will ship whenever I have time to get it finished.

**Closed by jcoglan** 2021-07-26 18:48 UTC

**Comment by lubieowoce** [comment] 2021-08-14 11:53
My bad, I didn't to check closed issues 😅 Wouldn't it make sense to keep one open just to stop people from opening new ones though?

(If you want to skip the noise of "hey it's still broken for me" comments, you could add a "i'll get to it when i get to it" comment and disable comments, I feel like that'd save everyone some time and effort!)

**Comment by lubieowoce** [comment] 2021-08-14 11:57
BTW if you're accepting contributions, I'd be happy to help getting the next version out! 🙂

**Comment by jcoglan** [comment] 2022-04-01 11:51
This should now be fixed as part of the v0.4 release; see https://blog.jcoglan.com/2022/04/01/announcing-canopy-0-4/
